config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  post '/expense', to: 'expenses#create'

  namespace :api do
    resources :expenses, only: %i[index create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::API
  end
end

app/controllers/api/expenses_controller.rb
module Api
  class ExpensesController < BaseController
    def index
      render json: { expenses: ::Expense.all }
    end

    def create
      expense = Expense.new(expense_params)

      if expense.save
        render json: { expense: expense }, status: :created
      else
        render json: { errors: expense.errors }, status: :unprocessable_entity
      end
    end

    private

    def expense_params
      params.require(:expense).permit(:amount, :category_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def create
    Expense.create(expense_params)
    redirect_to root_path
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :category_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :expense, :expenses, :total_amount

  private

  def expense
    @expense ||= Expense.new
  end

  def expenses
    @expenses ||= Expense.all
  end

  def total_amount
    @total_amount ||= Expense.sum(:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categories_names_ids
    [['Food', 1], ['Beauty', 2], ['Cinema', 3],['Gifts', 4]]
  end

  def category_id_to_name(id)
    categories_names_ids.find do |category|
      category[1] == id
    end[0]
  end
end

app/views/home/index.html.erb
<div id='t-add-expense-form'>
  <%= form_with model: expense, url: expense_path do |f| %>
    <%= f.text_field :amount %>
    <%= f.select :category_id, categories_names_ids %>
    <%= f.submit 'Add' %>
  <% end %>
</div>

<div id='t-expenses-list'>
  <table>
    <thead>
      <tr>
        <td>
          Amount
        </td>
        <td>
          Category
        </td>
        <td>
          When
        </td>
      </tr>
    </thead>
    <tbody>
      <% expenses.each do |expense| %>
        <tr id="t-expense-<%= expense.id %>">
          <td>
            <%= expense.amount %>
          </td>
          <td>
            <%= category_id_to_name(expense.category_id) %>
          </td>
          <td>
            <%= expense.created_at.to_date %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<div id="t-total-amount">
  <%= total_amount %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expenses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h2>Home expenses</h2>
  </header>
  <body>
    <%= yield %>
  </body>
</html>